Silverstripe 5 support
andrewandante/silverstripe-clippy pull request #33
Opened 2023-10-06 01:20 UTC by elliot-sawyer

* CMS 5
* silverstripe/admin already implied
* latest commonmark
* use any version of PHPunit (presumes ^9 if CMS 5 is used)

2023-10-06 03:29 UTC, andrewandante commented
Hi @elliot-sawyer - thanks for this PR! In the interest of not making this a major change, can we use `||`-style requirements?

2023-10-06 05:45 UTC, elliot-sawyer commented
@andrewandante fixed

2023-10-11 22:41 UTC, andrewandante requested changes

2023-10-11 22:41 UTC, andrewandante commented on composer.json
> +        "phpunit/phpunit": "*",
```suggestion
        "phpunit/phpunit": "^5.7 || ^9.5",
```

2023-10-11 22:41 UTC, andrewandante commented on composer.json
> +        "squizlabs/php_codesniffer": "*"
I don't think this needs to change?

2023-10-11 22:41 UTC, andrewandante commented on composer.json
> +        "silverstripe/cms": "^4 | ^5",
```suggestion
        "silverstripe/cms": "^4 || ^5",
```

Needs two pipes

2023-10-11 22:41 UTC, andrewandante commented on composer.json
> +        "phpunit/phpunit": "*",
Would prefer not to use wildcard matchers, even in `require-dev`

2023-10-27 05:34 UTC, elliot-sawyer commented
Hi mate, sorry for the delay, all issues have been noted and fixed  :+1:

2023-10-27 07:19 UTC, andrewandante approved these changes

2023-10-27 07:20 UTC, merged

2023-10-27 07:20 UTC, andrewandante commented
Amazing, thanks @elliot-sawyer !